"""empty message

Revision ID: 4af6c652fa15
Revises: 884cd8ef8cf5
Create Date: 2024-07-23 18:24:41.331409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af6c652fa15'
down_revision = '884cd8ef8cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('created')
        batch_op.drop_column('edited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
